"""
Scraper registry — maps every scraper to the CLI flags the launcher needs.

headful_mode:
  "flag"     → pass --headful to enable headed browser
  "inverted" → pass nothing (omitting --headless = headed by default)
  "default"  → already headed by default (HEADLESS=False constant), no flag needed
  "none"     → requests-based, no browser
"""

SCRAPERS = [
    # ── Pet / Animal ────────────────────────────────────────────────────────────
    {
        "id": "bensons_pet",
        "name": "Benson's Pet Center",
        "script": "bensons_pet/bensons_pet_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "inverted",   # default headless; omit --headless for headed
        "description": "Scrapes images & descriptions from shop.bensonspet.com by SKU",
    },
    {
        "id": "birdsland",
        "name": "Birds Land JO",
        "script": "birdsland/birdsland_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "inverted",
        "description": "Scrapes product data from birdslandjo.com by SKU",
    },
    {
        "id": "ferplast",
        "name": "Ferplast",
        "script": "ferplast/ferplast_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes images, characteristics & description from ferplast.com",
    },
    {
        "id": "parafarmaciapet",
        "name": "Parafarmacia Pet",
        "script": "parafarmaciapet/parafarmaciapet_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes description & images from parafarmaciapet.com by SKU",
    },
    {
        "id": "woolapet",
        "name": "Woola Pet",
        "script": "woolapet/woolapet_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes images & description from woolapet.com by SKU",
    },

    # ── Electronics ─────────────────────────────────────────────────────────────
    {
        "id": "anker_sg",
        "name": "Anker (Singapore)",
        "script": "ankar/anker_scraper_sg.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "none",
        "description": "Scrapes Anker Singapore store by SKU (requests-based, SKU verified)",
    },
    {
        "id": "anker_uk",
        "name": "Anker (UK)",
        "script": "ankar/anker_scraper_uk.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "none",
        "description": "Scrapes Anker UK store by SKU (requests-based, SKU verified)",
    },
    {
        "id": "anker_com",
        "name": "Anker (Global)",
        "script": "ankar/anker_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "none",
        "description": "Scrapes Anker global store by SKU (requests-based)",
    },
    {
        "id": "smartbuy",
        "name": "SmartBuy ME",
        "script": "smartBuy/smartbuy_scraper.py",
        "in_flag": "--in",
        "sku_flag": None,
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes images & description from smartbuy-me.com by barcode (SKU verified)",
    },
    {
        "id": "xiaomi_africa",
        "name": "Xiaomi MiStore Africa",
        "script": "xiaomiAfrica/mistore_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes title, description & images from mistore.africa by SKU",
    },
    {
        "id": "samix",
        "name": "Samix Electronics",
        "script": "samixelectronicsScraper/samix_scraper.py",
        "in_flag": "--input",
        "sku_flag": None,
        "out_flag": "--output",
        "headful_mode": "flag",
        "description": "Scrapes product data from Samix Electronics website",
    },
    {
        "id": "itead",
        "name": "ITEAD / SONOFF",
        "script": "itead/itead.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "default",
        "description": "Scrapes SONOFF/ITEAD product data by SKU",
    },

    # ── Hardware / Tools ────────────────────────────────────────────────────────
    {
        "id": "ronix",
        "name": "Ronix Tools",
        "script": "Ronix/RonixScrapper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes description & images from ronixtools.com by SKU",
    },
    {
        "id": "bashiti_hardware",
        "name": "Bashiti Hardware",
        "script": "bashitihardware/bashitihardware_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "inverted",
        "description": "Scrapes product data from Bashiti Hardware website",
    },
    {
        "id": "bashiti_central",
        "name": "Bashiti Central",
        "script": "bashiticentral/bashiticentral_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--output-file",
        "headful_mode": "flag",
        "description": "Scrapes product data from Bashiti Central website",
    },
    {
        "id": "ingco",
        "name": "Ingco Toolmart",
        "script": "ingcotoolmart/toolmartScraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes product data from Ingco Toolmart website",
    },
    {
        "id": "yato",
        "name": "Yato / Inserv.lv",
        "script": "yato_inserv/inserv.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes images & description from inserv.lv by SKU",
    },
    {
        "id": "total_jadever",
        "name": "Total JO / Jadever",
        "script": "total-jadever/totalScraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes product data from total-jo.com by barcode",
    },
    {
        "id": "zepter",
        "name": "Zepter JO",
        "script": "zepter/zepter_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes description from shop.zepter.com.jo by SKU",
    },

    # ── Home & Lifestyle ────────────────────────────────────────────────────────
    {
        "id": "doublem",
        "name": "Double M",
        "script": "doublem/doublem.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes product data from Double M website by SKU",
    },
    {
        "id": "organdle",
        "name": "Organdle",
        "script": "organdle/organdle_scraper.py",
        "in_flag": "--input",
        "sku_flag": None,
        "out_flag": "--output",
        "headful_mode": "flag",
        "description": "Scrapes product images from Organdle website",
    },
    {
        "id": "igloo",
        "name": "IGLOO",
        "script": "IGLOO/igloo_scraper.py",
        "in_flag": "--input",
        "sku_flag": None,
        "out_flag": "--output",
        "headful_mode": "inverted",
        "description": "Scrapes product data from IGLOO website",
    },
    {
        "id": "sistema",
        "name": "Sistema",
        "script": "Sistema/scrape_sistema_imgs.py",
        "in_flag": "--file",
        "sku_flag": None,
        "out_flag": None,
        "headful_mode": "none",
        "description": "Scrapes images for Sistema products",
    },
    {
        "id": "cosmoplast",
        "name": "Cosmoplast",
        "script": "Cosmoplast/fill_images_from_barecode.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "none",
        "description": "Fills product images from shop.cosmoplast.com by product name",
    },
    {
        "id": "titiz",
        "name": "Titiz",
        "script": "Titiz/titiz_scraper.py",
        "in_flag": "--input",
        "sku_flag": None,
        "out_flag": "--output",
        "headful_mode": "inverted",
        "description": "Scrapes product data from Titiz website",
    },
    {
        "id": "bestways",
        "name": "Best Ways",
        "script": "bestWays/bestWays.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes product data from bestways.com by model",
    },

    # ── Pharmacy / Health ────────────────────────────────────────────────────────
    {
        "id": "phc",
        "name": "PHC.com.jo",
        "script": "phc/phc_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes product data from phc.com.jo by SKU",
    },

    # ── General / Multi-store ───────────────────────────────────────────────────
    {
        "id": "arabi_mart",
        "name": "Arabi E-Mart",
        "script": "arabiMart/arabiMart.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes product data from arabimart.com by SKU",
    },
    {
        "id": "info_scraper",
        "name": "Arabi E-Mart (Info)",
        "script": "InfoScraper/InfoScraper.py",
        "in_flag": "--in",
        "sku_flag": None,
        "out_flag": "--out",
        "headful_mode": "inverted",
        "description": "Scrapes images & description from Arabi E-Mart by search query",
    },
    {
        "id": "hmg",
        "name": "HMG",
        "script": "hmg/hmgScraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": None,
        "headful_mode": "flag",
        "description": "Scrapes product data from HMG website by SKU",
    },
    {
        "id": "layor",
        "name": "Layor Group",
        "script": "layorGroup/layorGroup.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes product data from Layor Group website by SKU",
    },
    {
        "id": "jo_cell",
        "name": "JO Cell",
        "script": "JO CELL/jo_cell_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes product data from JO Cell website by SKU",
    },
    {
        "id": "amman_cart",
        "name": "Amman Cart",
        "script": "AmmanCart/AmmanCartScraper.py",
        "in_flag": "--input",
        "sku_flag": None,
        "out_flag": "--output",
        "headful_mode": "flag",
        "description": "Scrapes product data from ammancart.com",
    },
    {
        "id": "rcc",
        "name": "RCC",
        "script": "RCC/RCCScraper.py",
        "in_flag": "--input",
        "sku_flag": None,
        "out_flag": "--output",
        "headful_mode": "flag",
        "description": "Scrapes product data from RCC website",
    },
    {
        "id": "xmart",
        "name": "X Mart JO",
        "script": "X mart/XMartScraper.py",
        "in_flag": "--input",
        "sku_flag": "--item-col",
        "out_flag": "--output",
        "headful_mode": "flag",
        "description": "Scrapes title, description, images & product code from xmart.jo by item name",
    },
    {
        "id": "g_guard",
        "name": "G-Guard",
        "script": "G-Guard/gguard_scraper.py",
        "in_flag": "--input",
        "sku_flag": None,
        "out_flag": "--output",
        "headful_mode": "flag",
        "description": "Scrapes product data from G-Guard website",
    },
    {
        "id": "sahebshawar",
        "name": "Saheb Shawar",
        "script": "sahebshawar/sahebshawar_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "none",
        "description": "Scrapes images & description from sahebshawar.com by model (requests)",
    },
    {
        "id": "abdeen",
        "name": "Abdeen Center",
        "script": "abdeencenter/abdeencenter.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes product data from abdeencenter.com by barcode/SKU",
    },
    {
        "id": "tayo",
        "name": "Tayo",
        "script": "tayo/tayp.py",
        "in_flag": "--input",
        "sku_flag": "--sku-col",
        "out_flag": "--output",
        "headful_mode": "inverted",
        "description": "Scrapes product data from Tayo website by SKU",
    },
    {
        "id": "suppliers",
        "name": "Arabi E-Mart Suppliers",
        "script": "suppliers/suppliersScrappar.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "none",
        "description": "Finds first Google/DuckDuckGo result for each supplier name (Playwright)",
    },
    {
        "id": "newvision",
        "name": "New Vision",
        "script": "new vision/newvision_universal_scraper.py",
        "in_flag": "--skus-file",
        "sku_flag": "--sku-column",
        "out_flag": "--output",
        "headful_mode": "flag",
        "description": "Scrapes product data from New Vision website by SKU",
    },
    {
        "id": "ambro",
        "name": "Ambro-Sol",
        "script": "ambro/ambro_scraper.py",
        "in_flag": "--input",
        "sku_flag": None,
        "out_flag": None,
        "headful_mode": "none",
        "description": "Scrapes product data from Ambro-Sol website (requests-based)",
    },
    {
        "id": "fairuzy",
        "name": "Fairuzy JO",
        "script": "fairuzy/fairuzy_scraper.py",
        "in_flag": "--in",
        "sku_flag": "--sku-col",
        "out_flag": "--out",
        "headful_mode": "flag",
        "description": "Scrapes description & images from jo.fairuzy.com by product name",
    },




]

SCRAPERS_BY_ID = {s["id"]: s for s in SCRAPERS}
